name: flutter_soulmateelf
description: soulmateelf

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # IOS风格icon
  # https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons
  cupertino_icons: ^1.0.5
  # get框架
  # https://github.com/jonataslaw/getx
  get: ^4.6.5
  # 网络请求
  # https://github.com/flutterchina/dio
  dio: ^5.1.1
  # 本地存储
  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences
  shared_preferences: ^2.1.0
  # 上下拉组件
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0
  # 屏幕适配
  # https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.7.0
  # 图片预览
  # https://github.com/renancaraujo/photo_view
  photo_view: ^0.14.0
  # 获取app信息
  # https://github.com/flutter/plugins
  package_info_plus: ^3.0.3
  # 网络状态
  # https://github.com/flutter/plugins
  connectivity_plus: ^3.0.3
  # 拨打电话等
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^6.1.10
  # webview
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
  webview_flutter: ^4.0.7
  # 加载框-挺好看-还有toast-内部使用的是全局Overlay
  # https://github.com/nslog11/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 弹框
  # https://github.com/mono0926/adaptive_dialog
  adaptive_dialog: ^1.8.3
  # 日志
  # https://github.com/leisim/logger
  logger: ^1.3.0
  # 时间处理
  # https://github.com/sadespresso/moment_dart
  moment_dart: ^0.17.4
  # 缓存网络图片
  # https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.2.3
  #权限管理
  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^10.2.0
  #进度条
  #https://github.com/diegoveloper/flutter_percent_indicator/
  percent_indicator: ^4.2.3
  #键盘事件
  #https://github.com/MisterJimson/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.4.0
  #系统分享
  #https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/backGround/
    - assets/images/icons/

