name: soulmate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # IOS风格icon
  # https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons
  cupertino_icons: ^1.0.5
  # get框架
  # https://github.com/jonataslaw/getx
  get: ^4.6.5
  # 网络请求
  # https://github.com/flutterchina/dio
  dio: ^5.3.2
  # 本地存储
  # https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences
  shared_preferences: ^2.2.0
  # 上下拉组件
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0
  # 屏幕适配
  # https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.8.4
  # 自定义菜单
  # https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter
  animated_bottom_navigation_bar: ^1.3.0
  # 图片预览
  # https://github.com/renancaraujo/photo_view
  photo_view: ^0.14.0
  # 获取app信息
  # https://github.com/flutter/plugins
  package_info_plus: ^4.1.0
  # 网络状态
  # https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus/connectivity_plus
  connectivity_plus: ^5.0.0
  # 拨打电话等
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^6.1.12
  # webview
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
  webview_flutter: ^4.2.3
  # 加载框-挺好看-还有toast-内部使用的是全局Overlay
  # https://github.com/nslog11/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 弹框
  # https://github.com/mono0926/adaptive_dialog
  adaptive_dialog: ^1.9.0
  # 日志
  # https://github.com/leisim/logger
  logger: ^2.0.1
  # 时间处理
  # https://github.com/sadespresso/moment_dart
  moment_dart: ^1.1.0
  # 缓存网络图片
  # https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.2.3
  #权限管理
  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^10.4.3
  #键盘事件
  #https://github.com/MisterJimson/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.4.1
  #系统分享
  #https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
  share_plus: ^7.1.0
  #支持异步校验的表单
  #https://github.com/GiancarloCode/form_bloc
  flutter_form_bloc: ^0.31.0
  #验证码输入
  #https://github.com/adar2378/pin_code_fields
  pin_code_fields: ^8.0.1
  #语音转文字
  #https://github.com/csdcorp/speech_to_text
  speech_to_text: ^6.3.0
  #google登录
  #https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in
  google_sign_in: ^6.1.4
  #facebook登录
  #https://github.com/Innim/flutter_login_facebook
  # flutter_login_facebook: ^1.8.0
  # 图片上传
  # https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^1.0.2
  # 支付内购，flutter官方插件
  # https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase
  in_app_purchase: ^3.1.8
  # 动画
  # https://github.com/felixblaschke/simple_animations
  simple_animations: ^5.0.2
  # 滑动菜单
  #https://github.com/letsar/flutter_slidable
  flutter_slidable: ^3.0.0
  # 交错的瀑布流布局
  # https://github.com/letsar/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.7.0

  # 添加原生启动屏幕
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/image/
    - assets/images/icons/
    - assets/images/menuIcon/