name: soulmate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3


environment:
  sdk: '>=3.1.0 <4.0.0'

flutter_icons:
  image_path: "assets/images/image/icon.png"
  android: true
  ios: true

dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # IOS风格icon
  # https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons
  cupertino_icons: ^1.0.5
  # get框架
  # https://github.com/jonataslaw/getx
  get: ^4.6.6
  # 网络请求
  # https://github.com/flutterchina/dio
  dio: ^5.3.2
  # 本地存储
  # https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences
  shared_preferences: ^2.2.0
  # 上下拉组件
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0
  # 屏幕适配
  # https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.8.4
  # 自定义菜单
  # https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter
  animated_bottom_navigation_bar: ^1.3.0
  # 图片预览
  # https://github.com/renancaraujo/photo_view
  photo_view: ^0.14.0
  # 获取app信息
  # https://github.com/flutter/plugins
  package_info_plus: ^4.1.0
  # 网络状态
  # https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus/connectivity_plus
  connectivity_plus: ^5.0.0
  # 拨打电话等
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^6.1.12
  # webview
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
  webview_flutter: ^4.2.3
  # 加载框-挺好看-还有toast-内部使用的是全局Overlay
  # https://github.com/nslog11/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 弹框
  # https://github.com/mono0926/adaptive_dialog
  adaptive_dialog: ^1.9.0
  # 日志  和 声音录制播放插件有冲突 锁定到1.4
  # https://github.com/leisim/logger
  logger: 1.4.0
  # 时间处理
  # https://github.com/sadespresso/moment_dart
  moment_dart: ^1.1.0
  # 缓存网络图片
  # https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.2.3
  #权限管理
  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^10.4.3
  #键盘事件
  #https://github.com/MisterJimson/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.4.1
  #系统分享
  #https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
  share_plus: ^7.0.0
  #支持异步校验的表单
  #https://github.com/GiancarloCode/form_bloc
  flutter_form_bloc: ^0.31.0
  #验证码输入
  #https://github.com/adar2378/pin_code_fields
  pin_code_fields: ^8.0.1
  #语音转文字
  #https://github.com/csdcorp/speech_to_text
  speech_to_text: ^6.3.0
  #google登录
  #https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in
  google_sign_in: ^6.1.5
  # apple登录
  # https://pub-web.flutter-io.cn/packages/sign_in_with_apple
  sign_in_with_apple: ^5.0.0
  #facebook登录
  #https://github.com/darwin-morocho/flutter-facebook-auth
  # flutter_facebook_auth: ^6.0.2
  # 图片上传
  # https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^1.0.2
  # 支付内购，flutter官方插件
  # https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase
  in_app_purchase: ^3.1.11
  # google app广告
  # https://developers.google.com/admob/flutter/quick-start?hl=zh-cn
  #  google_mobile_ads: ^3.1.0
  # 消息推送
  # https://firebase.flutter.dev/docs/messaging/overview/
  firebase_messaging: ^14.7.5
  # 展示推送
  # https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications
  flutter_local_notifications: ^16.2.0
  # 动画
  # https://github.com/felixblaschke/simple_animations
  simple_animations: ^5.0.2
  # 滑动菜单
  #https://github.com/letsar/flutter_slidable
  flutter_slidable: ^3.0.0
  # 交错的瀑布流布局
  # https://github.com/letsar/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.7.0

  # 添加原生启动屏幕
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.3.5
  # 支持音频的播放和录制
  # https://pub-web.flutter-io.cn/packages/flutter_sound
  flutter_sound: ^9.2.13
  # 提供操作文件系统的API
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.1
  # 录音的动画效果
  # https://pub.dev/packages/awesome_ripple_animation
  awesome_ripple_animation: ^2.0.0
  # 音频播放的UI组件
  # https://pub.dev/packages/audio_waveforms
  audio_waveforms: ^1.0.4
  # 音频播放所需的文件系统插件
  # https://pub.dev/packages/file_picker
  file_picker: ^6.1.1
  # 点赞动效
  # https://pub.dev/packages/like_button
  like_button: ^2.0.5
  # 跳转外部链接插件
  # https://pub.dev/packages/launch_review
  launch_review: ^3.0.1
  # mqtt 消息订阅
  # https://pub.dev/packages/mqtt_client
  mqtt_client: ^10.0.0
  # 文本打字机效果
  # https://pub-web.flutter-io.cn/packages/animated_text_kit
  animated_text_kit: ^4.2.2
  # 轮播图效果
  # https://pub.dev/packages/card_swiper
  card_swiper: ^3.0.1
  # SQLite数据库
  # https://pub-web.flutter-io.cn/packages/sqflite
  sqflite: ^2.3.0
  # uuid
  # https://pub-web.flutter-io.cn/packages/uuid
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/image/
    - assets/images/icons/
    - assets/images/menuIcon/
    - assets/images/chatBackground/
    - assets/mp3/
    - assets/

  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
          style: italic
    - family: SFProRounded-Blod
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
    - family: SFProRounded-Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
    - family: SFProRounded-Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
    - family: PingFangRegular
      fonts:
        - asset: assets/fonts/PingFang-Regular.otf
    - family: SFProRounded-Light
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf