// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8jkZlhGfvJ6NF5lOL4OQZRoQBK33C9A',
    appId: '1:925869433707:android:eaa8e084c2b8d27d26a22e',
    messagingSenderId: '925869433707',
    projectId: 'soulmate-5cb6e',
    storageBucket: 'soulmate-5cb6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7QdgfRdCMJkOUg9LNGHpRZYyC-6lS_PQ',
    appId: '1:925869433707:ios:0b117bb42bdec59f26a22e',
    messagingSenderId: '925869433707',
    projectId: 'soulmate-5cb6e',
    storageBucket: 'soulmate-5cb6e.appspot.com',
    androidClientId: '925869433707-519irmsaobi7jrns25t0vgr8nni3bb71.apps.googleusercontent.com',
    iosClientId: '925869433707-h1qnkgftfojh2o1ao73fta4al97m4c8j.apps.googleusercontent.com',
    iosBundleId: 'com.soulmate.elf',
  );
}
