// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6I2uhV0znDIlYkpJ1MRhe1qHTVoFlM7I',
    appId: '1:133755992024:android:e2994f580ecb3caf5be4ad',
    messagingSenderId: '133755992024',
    projectId: 'soulmatesg-95589',
    storageBucket: 'soulmatesg-95589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxdENsVjDN7RPZkJ4qFz87eSwLzZuZ-g',
    appId: '1:133755992024:ios:bc0f5a7ae27cffba5be4ad',
    messagingSenderId: '133755992024',
    projectId: 'soulmatesg-95589',
    storageBucket: 'soulmatesg-95589.appspot.com',
    androidClientId: '133755992024-3n3ovva9c40e9mec28v21nk34df82ce4.apps.googleusercontent.com',
    iosClientId: '133755992024-3cmb7g6mjglgm8rl0v8ar8gtgmn9b0gf.apps.googleusercontent.com',
    iosBundleId: 'cn.soulmate.elf',
  );
}
